a = input("Digite algo: ")
print("O tipo primitivo desse valor é ",type(a))
if a.isspace(): print("É espaços em branco?  ")
if a.isnumeric(): print("É um número")
if a.isalpha(): print("É alfabético")
if a.isalnum(): print("É alfanumérico")
if a.isupper(): print("Está em MAIÚSCULO")
if a.istitle(): print("Está capitalizado")
if a.islower(): print("Está em minúsculo") 